### ISSUE TITLE
Indexer queue error

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack-server#179] opened 2015-11-18 00:34 UTC
Blockstore recovers from this error, but I'm reporting it here anyway so I can take a look at it later
---------
[DEBUG] [indexer:777] (75647) Stop building
Process PoolWorker-16:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 102, in worker
    task = get()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/queues.py", line 374, in get
    racquire()
OSError: [Errno 0] Error
[INFO] [virtualchain:88] (75647) 2 seconds
---------

**Comment by jcnelson** [comment] 2015-11-18 17:16
Looks like yet another unreproducable bug in the Python `multiprocess` module.

I've recently crossed the "straw that broke the camel's back" threshold for this particular module, so I'm making an in-house one for Blockstore.  It will also make it easy to keep memory usage down, since `multiprocess` does not `exec(2)` its workers (so they all inherit in-RAM copies of a lot of data that they don't need--in particular, the database).  Ours will.

**Comment by muneeb-ali** [comment] 2015-11-18 17:31
Looks like a [known bug in multiprocess](http://stackoverflow.com/questions/28591571/how-can-i-catch-a-memory-error-in-a-spawned-thread) that is fixed in Python 3.

**Comment by jcnelson** [comment] 2015-11-18 17:38
There's more to it than that, though--worker processes shouldn't be getting segfaults or aborting in the first place.  The workers aren't doing anything explicitly memory-unsafe--they're just issuing RPCs to bitcoind and feeding the results back to Blockstore.  I suspect it's the IPC mechanism itself that's buggy.

**Comment by muneeb-ali** [comment] 2015-11-18 17:49
Ah interesting. Wondering if we're hitting limits with Python ...

**Comment by jcnelson** [comment] 2015-12-04 16:08
Fixed in the `jude` branch of virtualchain.

**Comment by jcnelson** [comment] 2016-07-14 20:22
Fixed in the new stable release.

**Closed by jcnelson** 2016-07-14 20:22 UTC
Labels: bug, Fixed in the next release
